#!/usr/bin/lua

require "syslog"

print("option values:")
print("LOG_PID:    " .. syslog.LOG_PID)
print("LOG_CONS:   " .. syslog.LOG_CONS)
print("LOG_ODELAY: " .. syslog.LOG_ODELAY)
print("LOG_NDELAY: " .. syslog.LOG_NDELAY)
print("LOG_NOWAIT: " .. syslog.LOG_NOWAIT)
print("LOG_PERROR: " .. syslog.LOG_PERROR)

print("")
print("facility values:")
print("LOG_KERN:     " .. syslog.LOG_KERN)
print("LOG_USER:     " .. syslog.LOG_USER)
print("LOG_MAIL:     " .. syslog.LOG_MAIL)
print("LOG_DAEMON:   " .. syslog.LOG_DAEMON)
print("LOG_AUTH:     " .. syslog.LOG_AUTH)
print("LOG_SYSLOG:   " .. syslog.LOG_SYSLOG)
print("LOG_LPR:      " .. syslog.LOG_LPR)
print("LOG_NEWS:     " .. syslog.LOG_NEWS)
print("LOG_UUCP:     " .. syslog.LOG_UUCP)
print("LOG_CRON:     " .. syslog.LOG_CRON)
print("LOG_AUTHPRIV: " .. syslog.LOG_AUTHPRIV)
print("LOG_LOCAL0:   " .. syslog.LOG_LOCAL0)
print("LOG_LOCAL1:   " .. syslog.LOG_LOCAL1)
print("LOG_LOCAL2:   " .. syslog.LOG_LOCAL2)
print("LOG_LOCAL3:   " .. syslog.LOG_LOCAL3)
print("LOG_LOCAL4:   " .. syslog.LOG_LOCAL4)
print("LOG_LOCAL5:   " .. syslog.LOG_LOCAL5)
print("LOG_LOCAL6:   " .. syslog.LOG_LOCAL6)
print("LOG_LOCAL7:   " .. syslog.LOG_LOCAL7)

print("")
print("level values:")
print("LOG_EMERG:   " .. syslog.LOG_EMERG)
print("LOG_ALERT:   " .. syslog.LOG_ALERT)
print("LOG_CRIT:    " .. syslog.LOG_CRIT)
print("LOG_ERR:     " .. syslog.LOG_ERR)
print("LOG_WARNING: " .. syslog.LOG_WARNING)
print("LOG_NOTICE:  " .. syslog.LOG_NOTICE)
print("LOG_INFO:    " .. syslog.LOG_INFO)
print("LOG_DEBUG:   " .. syslog.LOG_DEBUG)
